### ISSUE TITLE
Corner Radius and Positioning

### ISSUE THREAD

**Issue by biocross** [lfroms/fluid-menu-bar-extra#11]
Hi, thanks for creating this amazing package! I was struggling with automatic re-size animations before I found this. 

For furthering customisation, I have two questions: 

- Can I change the corner radius of the panel? I tried setting a layer on the visual effect view of the panel, but that didn't work as expected.
- Can I change the position of the panel (like giving it an extra padding from the menu bar)?

Would really appreciate some guidance here. I'm happy to help create a PR to add a public facing API if there's a way to do these things.

**Comment by lfroms** [comment]
Hi @biocross!

The corner radius of the panel cannot be changed.  It is currently set to the smallest radius as configurable by public APIs.  There is a smaller corner radius used by `NSMenu` instances but it is not publicly accessible.

The positioning of the panel is currently set to emulate the behaviour of `NSMenu` or other menu bar extras, and is also not currently configurable.

I don't know much about your use case, but the goal of the package is to mimic system menu bar items as closely as possible, so I'm not sure if it would make sense to make either of those properties configurable?

**Comment by biocross** [comment]
Thanks for your response @lfroms!

My use case is actually to create a full menu bar app with this package, that has UI a lot of like the macOS control center. That's the reason I waned to customise the positioning and corner radius of the panel. 

Another question: Is there a way to hook into the popup open / close events - these callbacks can be super useful.

**Comment by lfroms** [comment]
I see... `FluidMenuBarExtra` is supposed to be as API compatible as possible to the first party `MenuBarExtra` so not sure if adding controls for corner radius would work well for that.

There is a way to hook into the open/close events using [`ScenePhase`](https://developer.apple.com/documentation/swiftui/scenephase) in any of your child views, for example:

```swift
struct MyView: View {
    @Environment(\.scenePhase) private var scenePhase

    var body: some View {
        Text("Content")
            .onChange(of: scenePhase) { newPhase in
                // Check newPhase
            }
     }
}
```

**Comment by biocross** [comment]
Fantastic, thanks a ton! If possible, I think it's worth documenting the snippet above in a small section on the README - it's a pretty common use case.

**Comment by lfroms** [comment]
There is a short mention of it in [_Key Features_](https://github.com/lfroms/fluid-menu-bar-extra#key-features) but no example.  That being said, `ScenePhase` is a first party API, so it should theoretically be intuitive.  I'll consider adding a more detailed example, though.
